FROM node:18

# Set working directory inside container to /usr/src/app
WORKDIR /usr/src/app

# Copy package.json and package-lock.json from src/web into container working dir
COPY backend/web/package*.json ./

# Install dependencies
RUN npm install

# Copy all source files from src/web into container
COPY backend/web/ .

# Expose your app port
EXPOSE 8080

# Start the app
CMD ["node", "app.js"]
